### ISSUE TITLE
[chassiss][pmon] implement cooling algorithm for chassis

### ISSUE THREAD

**Issue by arlakshm** [aristanetworks/sonic#50]
Enchance the cooling algorithm  to work for chassis

**Comment by rlhui** [comment]
Hi @arlakshm , wondering what's the priority of this one? And background of this? Thanks.

**Comment by kenneth-arista** [comment]
Basic cooling algo has been added via https://github.com/aristanetworks/sonic/commit/302c32be14c1dc2bb0bb5a01f8ff30dbfaab8422. More enhancements will be discussed with the community.

**Comment by Staphylo** [comment]
@arlakshm there's been some development in this area.
I'm refactoring our cooling algorithm so it can gather sensor information from `CHASSIS_STATE_DB`.
It should be ready in the coming weeks on `master` and `202305`.

**Comment by Staphylo** [comment]
Changes related to the cooling algorithm have merged in master and 202305.
Here is the PR for 202305 https://github.com/sonic-net/sonic-buildimage/pull/16702
The only thing that cannot be taken into account is the linecard transceivers temperatures since it's not available to the supervisor. Ideally these should be populated into `CHASSIS_STATE_DB` as well.
Marking this issue as solved.
